- pihole/Chart.yaml
- pihole/templates/deployment.yaml
- pihole/values.yaml
Allow the option to override the forward DNS server(s) that pihole will use.
> Override dns

- pihole/Chart.yaml
- pihole/templates/deployment.yaml
- pihole/values.yaml
See [the complete list](https://github.com/pi-hole/docker-pi-hole#environment-variables) for examples.
> allow chart user to specify any extra env variables to pass to pihole

- pihole/Chart.yaml
- pihole/templates/configmap-regex.yaml
- pihole/templates/deployment.yaml
- pihole/values.yaml
Adds a few features:
- DNS over HTTPs using cloudflared container
- Adds options to set regex.list for blacklisting
- Updates pihole version to latest
> Add cloudflared, regex, and update pihole

- pihole/Chart.yaml
- pihole/templates/deployment.yaml
- pihole/values.yaml
* Adjust probes settings to make them slightly less aggressive to prevent
unwanted restarts
* Make probes configurable via helm values
Fixes #21
> Tweaking probes settings

- pihole/Chart.yaml
- pihole/values.yaml
This will likely result in some linting errors that we can fix as part of this PR
> Bumping chart version to trigger CI

- charts/pihole/Chart.yaml
- charts/pihole/templates/_helpers.tpl
- charts/pihole/templates/deployment.yaml
- charts/pihole/templates/secret.yaml
- charts/pihole/values.yaml
Instead of setting a password in the values.yaml directly, now you have the option to use something like sealed secrets.
> Added option to override password secret

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/README.md.gotmpl
the configuration of metallb load balancers was wrong in the readme
> Updated Readme

- charts/pihole/Chart.yaml
- charts/pihole/values.yaml
fixes #41 - The existingClaim property was set to false. It has
to be set to the name of the existing claim
> existingClaim property wrong in values.yaml

- charts/pihole/Chart.yaml
- charts/pihole/values.yaml
> New pihole version

- charts/pihole/Chart.yaml
- charts/pihole/values.yaml
Version 5 of pi-hole was released.  Updating the image tag worked on my box so I think this is all that is needed to update the chart.
> Updating chart for v5 of pi-hole

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
Required for sensitive variables such as HTTP_PROXY.
Signed-off-by: Joseph Ball <joseph.ball@packetsolutions.io>
> Pull environment variables from kubernetes secrets.

- charts/pihole/Chart.yaml
- charts/pihole/templates/ingress.yaml
> do not append virtualHost

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
Support passing environment variables to the DoH container. This would allow you to customize the upsteam DoH service for example.
> Support passing env variables to the DoH container

- charts/pihole/Chart.yaml
- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
Signed-off-by: Noah Kontur <konturn@wustl.edu>
> Adds the option to include a sub-path for persistent volume mounts.

- charts/pihole/Chart.yaml
- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
Add ability to use a custom volume definition for the config volume (hostpath, nfs, etc ...)
> feat: Add custom volume for config

- charts/pihole/Chart.yaml
- charts/pihole/values.yaml
> Bump version to 5.1.2

- charts/pihole/Chart.yaml
- charts/pihole/values.yaml
> Update Pi-hole to version 5.2.1 and increment Chart revision

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/templates/configmap-static-dhcp.yaml
- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
Added a configmap to modify dhcp configuration
Thanks @OnekO
> Added static dhcp config

- .github/workflows/lint-test.yaml
- charts/pihole/Chart.yaml
- charts/pihole/templates/deployment.yaml
- charts/pihole/templates/service-web.yaml
use metrics on cloudflared for liveness, add pihole_port on exporter
> use metrics on cloudflared for liveness, add pihole_port on exporter

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/values.yaml
fixes #127
Signed-off-by: Christian02 Erhardt <christian.2.erhardt@continental.com>
> Update pi-hole to 5.2.4

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/templates/configmap-ftl.yaml
- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
Adds configmap for `/etc/pihole/pihole-FTL.conf`. I needed a way to set `MAXDBDAYS: 14`
> Adds configmap for pihole-FTL.conf

- charts/pihole/Chart.yaml
- charts/pihole/README.md
This removes the appVersion and closes #152.
I tested it in my installation already.
> chore: remove appVersion

- .all-contributorsrc
- README.md
- charts/pihole/README.md
- charts/pihole/README.md.gotmpl
- charts/pihole/values.yaml
Added contributors and extended documentation
> Documentation

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
Thanks a lot for creating and maintaining this chart, it helped me a lot with my setup ❤️.
* Update `pihole` to the latest `2021.10.1`
* Make use of the chart's `appVersion` field to make it easier to update the version in the future and to be more in-line with the latests charts best-practices
> Update pihole and make use of appVersion

- charts/pihole/Chart.yaml
upgrade to the latest version of the container for the month of Feb
> set the appVersion to 2022.02.01 and version to 2.5.7

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/README.md.gotmpl
* Added generation of documentation
* Updated Release workflow
> Update Github Actions

- charts/pihole/Chart.yaml
- charts/pihole/values.yaml
I updated the ekofr/pihole-exporter image tag to v0.3.0.
> updated ekofr/pihole-exporter tag to v0.3.0

- .all-contributorsrc
- .github/workflows/lint-test.yaml
- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
Switch to a real check of functionality and allow customization
> Custom DoH liveness probe & better default check

- .github/workflows/lint-test.yaml
- charts/pihole/examples/k3s-values.yaml
When setting up pihole i could have really used more examples of the values.yaml. So here it is:  
Im now running this on my k3s raspberry pi cluster.
(ofc the password is not real 😄)
> example values for k3s 

- .all-contributorsrc
- README.md
- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/README.md.gotmpl
Updated pihole version to 2022.05
> chore: update Pi-hole version to 2022.05

- .all-contributorsrc
- README.md
- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/README.md.gotmpl
- package-lock.json
- package.json
chore: Updated all contributors
> feat: Updated pihole version to 2024.01.0

- charts/pihole/values.yaml
A commit to trigger a new release for release please
- fixes #
> feat: Change to trigger a new Release

- charts/pihole/Chart.yaml
Change default branch in chart.yaml
- fixes #
> fix: Update Chart.yaml

- charts/pihole/templates/NOTES.txt
added some more meaningful text to Notes.txt
fixes #307
> fix: Update Notes.txt

- index.yaml
The icon was not working, changed it to a wiki commons source
> chore: update icon in index.yaml

- charts/pihole/values.yaml
The documentation should be string not a list
- fixes #318
> fix: wrong customSettings.otherSettings exmaple in values.yaml

- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
This PR adds a new parameter `doh.command` to specify the command to pass to the `cloudflared` container. 
This allows to use the official docker image [cloudflared](https://hub.docker.com/r/cloudflare/cloudflared) maintained by Cloudflare by setting the command to `proxy-dns`.
This should help fix #247
> feat: allow to override the command of the cloudflared container.

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
Support PiHole v6
Concurrency and helps with #342 
One thing to consider is that liveness probes have been changed to force HTTPS by default
- fixes #
> feat: PiHole v6 Support

- charts/pihole/templates/deployment.yaml
fixes https://github.com/pi-hole/docker-pi-hole/issues/1709
expose web on non-standard ports
> fix: expose webui on non-standard port

- example/values.yaml
> fix: Update values.yaml

- charts/pihole/values.yaml
https breaks some installations and stops the lint testing from working
- fixes #356
> fix: revert liveness and readiness probe back to http

- README.md
Revert changes in README file that was made in https://github.com/MoJo2600/pihole-kubernetes/pull/351/files.
Keep the correct information about the project, how to use it and contributors.
none
none
none
> docs: revert to previous readme

- .all-contributorsrc
- .devcontainer/devcontainer.json
- README.md
- charts/pihole/README.md
- charts/pihole/README.md.gotmpl
- package-lock.json
> chore: update all contributors

- .github/workflows/release-please.yaml
- charts/pihole/Chart.yaml
Upgrade release please and fix missing icon
- fixes #
> chore: new release please, icon
