MoJo2600/pihole-kubernetes

- pihole/Chart.yaml
- pihole/values.yaml
* Setting the chart 'appimage' to the current pihole version
* Specifying the multi-arch image tag instead of opinionated amd64-only tagged image.  See [the docker hub tag info](https://hub.docker.com/r/pihole/pihole/tags/) for more details.
> fixing image tag and app version

- pihole/Chart.yaml
- pihole/templates/deployment.yaml
readiness and livenessProbes are indented too far. They belong to the container element, not the ports list
Fixes #12
> fix: Adjust readiness/liveness probe indentation

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- README.md
- ct.yaml
- pihole/Chart.yaml
- pihole/README.md
Inspired by [this example repo](https://github.com/helm/chart-testing-action), this PR should implement GitHub Actions support which will:
* For every PR impacting the helm chart, a linter will make sure that the change passes linting which includes forcing a version bump on changes)
* For every PR impacting the helm chart, a 'kubernetes in docker' (KIND) cluster will be temporarily created and the chart will be installed to that test cluster to ensure that it installs properly
* For every merge to master impacting the helm chart, automation will package the chart, update the `index.yaml` on the `gh-pages` branch, and cut a github release with the packaged chart for reference as a chart repository.
**ACTION REQUIRED:**
* Github Pages should be enabled within the repo settings. Please use …
> Implement Github Actions

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/templates/ingress.yaml
- charts/pihole/values.yaml
Ingress was not working with Helm v3 (did not test with v2) without a change to this reference.
While working in this space I was getting some warnings about type issues and updated those values to the types expected by the API.
> Resolving issue with template access in ingress

- README.md
The README didn't include info on chart values etc. I found that info from hub.helm.sh very useful, so proposing to link it from README.
> Add link to hub.helm.sh entry with chart info

- charts/pihole/Chart.yaml
- charts/pihole/templates/deployment.yaml
- charts/pihole/templates/service-tcp.yaml
- charts/pihole/templates/service-udp.yaml
- charts/pihole/values.yaml
Hi,
First of all, thank you for the hard work building this Helm chart!
I'm author of a [guide about self-hosting](https://kauri.io/build-your-very-own-selfhosting-platform-with-rasp/5e1c3fdc1add0d0001dff534/c) with RapsberryPi boards and Kubernetes (k3s) and I wrote some articles on how to self-host applications and a specific one about [Pi-Hole using your chart](https://kauri.io/68-selfhost-pihole-on-kubernetes-and-block-ads-and/5268e3daace249aba7db0597b47591ef/a).
In this Pull-Request, I made a few improvements, mostly in the case when your router doesn't allow you to override the DNS address, so we have to disable DHCP on the router and enable it on Pi-Hole. However, in order to work (network broadcast on port 67), one of the solution consists in running the pod in **host networking …
> Some improvements

- charts/pihole/Chart.yaml
- charts/pihole/templates/deployment.yaml
- charts/pihole/templates/ingress.yaml
- charts/pihole/values.yaml
Pihole, uses default virtualhost `pi.hole`, if ingress is set with a
different name static assets no longer gets loaded since all the static
assets are still requested with `pi.hole`.
The change will bring in support for specifying different virtualhost
and use it ingress by default
Signed-off-by: Krishnaswamy Subramanian <jskswamy@gmail.com>
> Add support for virtual host

- charts/pihole/Chart.yaml
- charts/pihole/templates/configmap.yaml
- charts/pihole/values.yaml
Add ability for this chart to support upstream DNS server to be configured with dnsmasq.
Signed-off-by: Krishnaswamy Subramanian <jskswamy@gmail.com>
> Add support for upstream DNS server

- charts/pihole/Chart.yaml
- charts/pihole/templates/deployment.yaml
Any of the following configuration modification
requries restart to pihole for it to reload the configurations
- adlists
- blacklist
- regex
- whitelist
- dnsmasq
Necessary annotations have been added to the deployment template
metadata section to reflect any changes to the configurations
Signed-off-by: Krishnaswamy Subramanian <jskswamy@gmail.com>
> Restart pihole when config are changed

- charts/pihole/Chart.yaml
- charts/pihole/templates/ingress.yaml
Without this patch, an ingress config will fail bacause of nested ranges confuses virtualHost value
> Fix ingress template tls section

- charts/pihole/Chart.yaml
- charts/pihole/templates/configmap-regex.yaml
regex ConfigMap incorrectly checks for existence of blacklist values. This PR fixes that to allow regex list without having a dependency on the blacklist
Thanks @arpankapoor I updated the code and bumped the version to merge the fix for this bug
> Arpankapoor regex configmap fix

- charts/pihole/templates/configmap-regex.yaml
`regex` ConfigMap incorrectly checks for existence of `blacklist` values. This PR fixes that to allow `regex` list without having a dependency on the `blacklist`
> Fix configmap-regex condition

- charts/pihole/Chart.yaml
- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
Add antiaffinity in deployement to avoid other pihole helm release scheduled in the same node.
> Add antiaffinity option to deployment

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/ci/monitoring-values.yaml
- charts/pihole/templates/deployment.yaml
- charts/pihole/templates/servicemonitor.yaml
- charts/pihole/templates/tests/test-pihole-endpoint.yml
- charts/pihole/values.yaml
Adding optional [eko/pihole-exporter](https://github.com/eko/pihole-exporter), as sidecar container for better [prometheus](https://prometheus.io/) integration.
> adding prometheus sidecar container and service monitor support

- charts/pihole/Chart.yaml
- charts/pihole/templates/service-tcp.yaml
Adds the prometheus port to the tcp service if the monitoring sidecar is enabled. Allows prometheus to scrape the target by dns name (e.g. `pihole:9617`) instead of IP address.
Resolves MoJo2600/pihole-kubernetes#84
> Add the prometheus port to the tcp service

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/templates/deployment.yaml
- charts/pihole/templates/tests/test-pihole-endpoint.yml
- charts/pihole/values.yaml
Allow users to configure doh liveness. This will help trouble shooting issues similar to https://github.com/MoJo2600/pihole-kubernetes/issues/98
> make doh liveness configurable

- .github/workflows/release.yaml
Release generation does not work because of wrong urls
> Fixed wrong helm urls

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/values.yaml
I hope I've done this the right way. Please let me know if it needs any changes.
This changes pi-hole to the latest 5.2.3 release.
Specific versions from the footer of the UI:
- Pi-hole v5.2.3
- Web Interface v5.3
- FTL v5.4
> Update pi-hole to 5.2.3

- README.md
The `--name` flag appears to be no longer valid in Helm
> --name invalid

- charts/pihole/Chart.yaml
- charts/pihole/templates/configmap.yaml
DHCP leases will contain the loadbalancer IP as DNS server. If the pod is rescheduled in this scenario DNS will still work. 
Tested on my local cluster with purelb as loadbalancer.
> set loadbalancer ip as DNS server for dhcp leases if available

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/templates/deployment.yaml
- charts/pihole/templates/service-web.yaml
- charts/pihole/values.yaml
This PR makes the following configurable:
- The web service ports - this is useful in situations when an alternative load balancer implementation like Rancher's ServiceLB is used: https://rancher.com/docs/k3s/latest/en/networking/#service-load-balancer
- `hostPort` for DNS - can be useful when using a LoadBalancer type service is not an option
- strategy type for Deployment - can to be set to `Recreate` to avoid PVC binding issues on clusters with multiple hosts
> Configurable web service ports, host port and deployment strategy type

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
Added support for custom Pod annotations passed from Helm values.
Examples given for prometheus scrape annotations, possibly replacing the need of PodMonitor.
> allow custom pod annotations

- charts/pihole/.helmignore
- charts/pihole/Chart.yaml
- charts/pihole/templates/deployment.yaml
- charts/pihole/templates/podmonitor.yaml
- example/README.md
Hi @MoJo2600, thanks for making this Helm chart so I don't have to! :D
I found some small fixes while inspecting the Helm chart that I submit in this PR as four separate commits.
- Update .helmignore to not package unused files
- Restart on change to ftl configmap
- Fix documentation typo
- Fix formatting bug for monitoring.podMonitor.labels
---
Not part of this PR as I wasn't confident about it, but I would think that the /docs folder and the /example folder should be deleted from the repo at this point in time.
I was also very confused about this reference, I think these lines can be deleted but they may be used by the later referenced action but I don't think they are.
https://github.com/MoJo2600/pihole-kubernetes/blob/f04bdbf3818701435dba0e2619ddfac5e91303d8/.github/workflows/release.y …
> Misc non-critical fixes

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/templates/service-dns-udp.yaml
- charts/pihole/templates/service-dns.yaml
- charts/pihole/values.yaml
add support for mixed DNS service (TCP and UDP)
keeping backwards compatibility by introducing `serviceDns.mixedService`.
---
fixes #78 
fixes #178
> support mixed TCP and UDP DNS service

- charts/pihole/Chart.yaml
- charts/pihole/templates/deployment.yaml
This migrates to the new env-vars, while keeping the same "DNS1" and "DNS2" options (so should no cause any breaking changes).
> Migrate to new DNS env vars

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/templates/service-dhcp.yaml
- charts/pihole/templates/service-dns-tcp.yaml
- charts/pihole/templates/service-dns-udp.yaml
- charts/pihole/templates/service-dns.yaml
- charts/pihole/templates/service-web.yaml
- charts/pihole/values.yaml
This PR adds support for dualstack use cases.
If the service type is `LoadBalancer` and `dualStack.enabled` is `true` separate loadbalancer services will be created (one for IPv4 and one for IPv6).
If a different service type is being used the services will use `"ipFamilies": ["IPv4", "IPv6"]` and `"ipFamilyPolicy": "PreferDualStack"`.
The `loadBalancerIP` field for the IPv6 services can also be set.
> Add dualstack service support

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
I've added support to set the hostname of the pod in order to better identify pihole instances.
The hostname is displayed in the top right corner of the pihole dashboard.
> Support to set hostname of pod

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/values.yaml
The docker-pi-hole team have introduced a new versioning scheme: Here's a quote from the [release notes](https://github.com/pi-hole/docker-pi-hole/releases/tag/2021.09):
> Previously, we have picked a version number of one of the internal components (most recently, FTL) and applied that to the docker container's tag. However, this sometimes causes confusion between users, but also developers (when we are not sure what to tag a docker release if FTL's version number has not changed)
> 
> **Going forward, we will use a year.month[.revision] to tag docker releases with.** To tag a new image, it is as simple as looking at the calendar to decide what the tag name should be. We will always try to leave any major changes until a new month rolls over. e.g if Pi-hole v6 were to be released in 2 …
> Latest docker image - using new versioning scheme!

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/values.yaml
Pi-Hole just released their (first) October release, tag 2021.10. I updated the manifests to use this image.
Link to the changelog: [docker-pi-hole Release 2021.10](https://github.com/pi-hole/docker-pi-hole/releases/tag/2021.10)
> Updated image tag to pihole October release (2021.10)

- charts/pihole/Chart.yaml
- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
Since pihole can be a critical service on the network, this PR makes it possible to make the pihole pod a high priority one so that the network does not go down in the absence of cluster resources.
> Feature: Add support for priorityClassName

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
This PR adds the ability to have extra volumes into the container so it's possible to change other files.
I'm currently using this to change the `/etc/lighttpd/external.conf` file to allow adding an FQDN to the web-ui, and also to mount the SSL certificates to be used by it that are generated by `cert-manager`.
But this can be useful for many other purposes.
* Add support for extraVolumes and extraVolumeMounts
This is how I'm using this feature.
```
extraVolumes:
lighttpd-external-conf:
hostPath:
path: /mnt/storage/pi-hole/etc/lighttpd/external.conf
lighttpd-ssl:
secret:
secretName: pi-hole-cert
extraVolumeMounts:
lighttpd-external-conf:
mountPath: /etc/lighttpd/external.conf
lighttpd-ssl:
mountPath: /etc/lighttpd/ssl
```
> Add support for extraVolumes and extraVolumeMounts

- classic/deployment-pihole.yml
error: unable to recognize "pihole/deployment-pihole.yml": no matches for kind "Deployment" in version `extensions/v1beta1`
using `apiVersion: apps/v1` works fine
> fix: using apps/v1 instead beta version

- .all-contributorsrc
- README.md
- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/README.md.gotmpl
- charts/pihole/templates/service-dhcp.yaml
- charts/pihole/templates/service-web.yaml
- charts/pihole/values.yaml
- package.json
This PR allows to explicitly set a `nodePort` for the dhcp and web services.
Additionally, it makes the dhcp port configurable.
> Add nodeport options for dhcp and web and make dhcp port configurable

- charts/pihole/Chart.yaml
- charts/pihole/templates/deployment.yaml
With the latest release the old/broken probe paths stopped working. Fixes #177
> Fix path of probes

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
I run two copies of pihole using the pihole helm chart in two different namespaces. To prevent pods from either namespace landing on the same node there needs to be an option to set namespaces in scope for anti-affinity.
> Add Support for anti-affinity settings across user defined namespaces

- charts/pihole/Chart.yaml
- charts/pihole/templates/deployment.yaml
Resolves a bug where you cannot add your own CNAMEs in the UI because of file ownership issues from mounting in the configmap as root. Here, like the other entries if we don't set any of our own it just shouldn't set the file.
> Only include custom CNAME file if any are set

- charts/pihole/Chart.yaml
- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
I have a container that I use to run a process to monitor the Pihole logs for specific DNS queries. The container uses a shared volume created on /var/log/pihole. I currently cannot use this Helm chart because there is no way to add my own container. 
This pull request simply adds the ability to add any number of containers via values.yaml. 
It passes LINT and I was able to successfully run my fork of the Helm chart to get my secondary container running within the Pihole pod.
This is my first ever contribution to any Github project. Please be gentle, but feedback is appreciated.  :)
> Add the ability to add extra containers to the Pihole pod

- charts/pihole/Chart.yaml
- charts/pihole/README.md
- charts/pihole/templates/deployment.yaml
- charts/pihole/templates/secret.yaml
- charts/pihole/values.yaml
Adds option `admin.enabled` (default true) which if set to false disables admin password.
Closes: #251 
Follows similar approach to taken by PR #261 but does not create secret if admin password is disabled.
From my understanding [suggestion](https://github.com/MoJo2600/pihole-kubernetes/pull/261#issuecomment-1611632540) made on PR #261 will not work as there is no way to distinguish value not set and value set to empty string in golang/helm templates. Hence why additional `admin.enabled` or `disablePassword` field is required.
> feat: add ability to disable admin password

- charts/pihole/templates/service-dhcp.yaml
- charts/pihole/templates/service-dns-tcp.yaml
- charts/pihole/templates/service-dns-udp.yaml
- charts/pihole/templates/service-dns.yaml
- charts/pihole/templates/service-web.yaml
- charts/pihole/values.yaml
This PR adds support for adding extra labels to the services templates, these extra labels can be used to set up services integrations (e.g.: CiliumLoadBalancerIPPool can use labels to select services)
> feat: add support for service extraLabels

- charts/pihole/templates/service-web.yaml
The `pihole-web` service is now valid when both `serviceWeb.http` and `serviceWeb.https` are disabled. Without this change, setting both of these to false will result in an invalid service manifest with an empty `spec.ports` value.
This change prevents the creation of the web service manifest if both `serviceWeb.http.enabled` and `serviceWeb.https.enabled` are `false`. Setting either of these values to true (the default) will preserve existing behaviour.
Allows the user to not expose the pihole web service by disabling both http and https in the `serviceWeb` configuration option.
> fix: invalid web service manifest generation

- charts/pihole/docs/Values.md
- charts/pihole/templates/secret.yaml
- charts/pihole/values.yaml
Adds the `admin.annotations` value for adding annotations to the admin password `Secret`.
By allowing annotations to be added to the password secret, we can use tools like [Reflector](https://github.com/emberstack/kubernetes-reflector) to synchronize secrets across namespaces. 
This is interesting e.g. with the [ExternalDNS](https://github.com/kubernetes-sigs/external-dns) 0.14+'s Pi-Hole integration that can automatically expose Ingress host names to the Local DNS configuration:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: external-dns
spec:
strategy:
type: Recreate
selector:
matchLabels:
app: external-dns
template:
metadata:
labels:
app: external-dns
spec:
serviceAccountName: external-dns
containers:
- name: external-dns
image: …
```
> feat: Add optional annotations to the password secret

- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
* [`charts/pihole/templates/deployment.yaml`](diffhunk://#diff-30e0453700126a81330cdd1bf42c61938bbdbfb1f157121c4caf475a10d654e4R227-R235): Added support for configuring the readiness probe type as either `httpGet` or `command`. If the type is set to `command`, the readiness probe will execute a specified command.
* [`charts/pihole/values.yaml`](diffhunk://#diff-74c171d443ba82ea3b11a6f0d7f77e42d4b01bc2768c3ef9dbe3694acc4a064dR186-L193): Introduced a new `type` parameter for the readiness probe configuration, defaulting to `httpGet` but can be set to `command`. Updated comments to improve clarity on the purpose of each configuration parameter.] 
With this configuration we can avoid the problem reported in issue #301
With the current configuration, the default value is not changed, …
> feat: add command option to set up readiness probe.

- charts/pihole/templates/deployment.yaml
- charts/pihole/templates/service-dhcp.yaml
- charts/pihole/templates/service-dns-tcp.yaml
- charts/pihole/templates/service-dns-udp.yaml
- charts/pihole/templates/service-dns.yaml
- charts/pihole/templates/service-web.yaml
I added the label `app.kubernetes.io/name` to deployment and services.
This label is among the [recommended ones](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels). It also enables the kubernetes integration with [homepage](https://gethomepage.dev/configs/kubernetes/).
> feat: Add recommanded label app.kubernetes.io/name

- charts/pihole/README.md
- charts/pihole/templates/ingress.yaml
- charts/pihole/values.yaml
Add a value for the ingress [pathType](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types).
I kept the default value the same to avoid any breaking changes, but I think Prefix might be a better default.
> feat: configurable pathType for the ingress resource

- charts/pihole/examples/dhcp-values.yaml
Add an example when using the DHCP server. This configuration is a bit trickier since:
1. It only works on the `hostNetwork`.
2. It may conflict with the host's `systemd-resolved`.
This example allows others to use this Helm Chart with DHCP enabled. This is useful if you are one of those poor souls whose router doesn't allow you to change the DNS server, so you have to disable your router's DHCP server.
This is really just an example. It still requires some skills to get it right.
- fixes #18 
Thank you for this chart! It was a fun Saturday project trying it out.
> docs: Add example with DHCP server

- charts/pihole/templates/deployment.yaml
- charts/pihole/templates/podmonitor.yaml
- charts/pihole/values.yaml
- Add readiness probe to cloudflared proxy (doh)
- Add podMonitor to cloudflared proxy (doh)
- Have readiness probe
- Ability to scrape metrics using podMonitor
- fixes #
> feat: cloudflared(doh) - add support for podmonitor and readiness

- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
TL;DR Allow the user to set a custom set of annotations for the pi-hole deployment in addition to pod-level annotations.
When editing config maps (especially the whitelist), I would like to avoid having to re-run gravity via UI. The [reloader](https://github.com/stakater/Reloader) controller does this job perfectly, but requires an annotation at the deployment level, an annotation at the pod level does not work. This PR adds the option to supply an optional arbitrary set of annotations for the deployment.
Users can now add custom annotations to the deployment in addition to other resources.
- partly implements #219
- unfortunately does not fix #134 (if using reloader and persistent storage)
> feat: add custom deployment annotation option

- charts/pihole/templates/service-dhcp.yaml
- charts/pihole/templates/service-dns-tcp.yaml
- charts/pihole/templates/service-dns-udp.yaml
- charts/pihole/templates/service-dns.yaml
- charts/pihole/templates/service-web.yaml
- charts/pihole/values.yaml
This change introduces the ability to specify `loadBalancerClass` for Kubernetes Services of type `LoadBalancer` within the Pi-hole Helm chart.
It involves:
1.  Adding a new optional `loadBalancerClass` field to the `serviceDns`, `serviceDhcp`, and `serviceWeb` sections in the `charts/pihole/values.yaml` file.
2.  Modifying the corresponding service template files (`charts/pihole/templates/service-dhcp.yaml`, `charts/pihole/templates/service-dns-tcp.yaml`, `charts/pihole/templates/service-dns-udp.yaml`, `charts/pihole/templates/service-dns.yaml`, and `charts/pihole/templates/service-web.yaml`) to include the `spec.loadBalancerClass` field in the Service manifest. This field is only rendered if the service `type` is `LoadBalancer` and a `loadBalancerClass` value is provided.
This change …
> feat: Allow specifying loadBalancerClass for LoadBalancer services

- charts/pihole/templates/deployment.yaml
When overriding `FTLCONF_webserver_port` via the `extraEnvVars`, a duplicate key is produced. This change checks if that variable is defined in `extraEnvVars` and if so, defers to that definition.
Allows users to modify the currently hardcoded `FTLCONF_webserver_port` value.
Advanced/niche use case, could be difficult to use for beginners.
Fixes #371
> fix: prioritize webserver_port in extraEnvVars

- charts/pihole/templates/deployment.yaml
- charts/pihole/values.yaml
Added configurable `spec.revisionHistoryLimit` parameter to the Pi-hole deployment template. This change allows users to customize the number of old ReplicaSets that Kubernetes retains for rollback purposes through the `values.yaml` file, providing better control over cluster resource usage and deployment history management.
- **Resource optimization**: Users can reduce the number of stored ReplicaSets from the default 10 to a lower number (e.g., 3), saving cluster storage and reducing clutter
- **Customizable deployment history**: Provides flexibility to adjust revision history based on specific operational needs and rollback requirements
- **Better resource management**: Especially beneficial in resource-constrained environments where minimizing stored objects is important
- **Maintains …
> feat: add spec.revisionHistoryLimit to deployment.yaml template
